In [1]:
from sklearn.feature_extraction.text import CountVectorizer
d1="I love programming"
d2="programming is intresting"
d3="I love pizza very very much"
documents=[d1,d2,d3]
vectorizer=CountVectorizer()
X=vectorizer.fit_transform(documents)
print(vectorizer.vocabulary_)
print(X.toarray())

{'love': 2, 'programming': 5, 'is': 1, 'intresting': 0, 'pizza': 4, 'very': 6, 'much': 3}
[[0 0 1 0 0 1 0]
 [1 1 0 0 0 1 0]
 [0 0 1 1 1 0 2]]


In [2]:
#print 20% data
import pandas as pd
df=pd.read_csv('newsgroups_test.csv')
print(df.iloc[0:20])

                                                 text  target       category
0   From: mccall@mksol.dseg.ti.com (fred j mccall ...       2      sci.space
1   From: "Changyaw Wang" <wangc@cs.indiana.edu>\n...       1  comp.graphics
2   From: lioness@maple.circa.ufl.edu\nSubject: Te...       1  comp.graphics
3   From: hotopp@ami1.bwi.wec.com (Daniel T. Hotop...       1  comp.graphics
4   From: Ad-Robot@bobsbox.rent.com (Robotic Posti...       1  comp.graphics
5   From: lee@hobbes.cs.umass.edu (Peter Lee)\nSub...       1  comp.graphics
6   From: gck@aero.org (Gregory C. Kozlowski)\nSub...       0    alt.atheism
7   From: PHARABOD@FRCPN11.IN2P3.FR\nSubject: Fran...       2      sci.space
8   From: wingo%cspara.decnet@Fedex.Msfc.Nasa.Gov\...       2      sci.space
9   From: nsmca@aurora.alaska.edu\nSubject: Combo ...       2      sci.space
10  From: gcdcrgm@state.systems.sa.gov.au\nSubject...       1  comp.graphics
11  From: aaron@minster.york.ac.uk\nSubject: Re: D...       0    alt.atheism

In [3]:
import pandas as pd
f=pd.read_csv('newsgroups_test.csv')
f.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1102 entries, 0 to 1101
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   text      1102 non-null   object
 1   target    1102 non-null   int64 
 2   category  1102 non-null   object
dtypes: int64(1), object(2)
memory usage: 26.0+ KB


In [4]:
#load 20 
df=pd.read_csv('newsgroups_test.csv')
print(df.iloc[0:20])
df.info()

                                                 text  target       category
0   From: mccall@mksol.dseg.ti.com (fred j mccall ...       2      sci.space
1   From: "Changyaw Wang" <wangc@cs.indiana.edu>\n...       1  comp.graphics
2   From: lioness@maple.circa.ufl.edu\nSubject: Te...       1  comp.graphics
3   From: hotopp@ami1.bwi.wec.com (Daniel T. Hotop...       1  comp.graphics
4   From: Ad-Robot@bobsbox.rent.com (Robotic Posti...       1  comp.graphics
5   From: lee@hobbes.cs.umass.edu (Peter Lee)\nSub...       1  comp.graphics
6   From: gck@aero.org (Gregory C. Kozlowski)\nSub...       0    alt.atheism
7   From: PHARABOD@FRCPN11.IN2P3.FR\nSubject: Fran...       2      sci.space
8   From: wingo%cspara.decnet@Fedex.Msfc.Nasa.Gov\...       2      sci.space
9   From: nsmca@aurora.alaska.edu\nSubject: Combo ...       2      sci.space
10  From: gcdcrgm@state.systems.sa.gov.au\nSubject...       1  comp.graphics
11  From: aaron@minster.york.ac.uk\nSubject: Re: D...       0    alt.atheism

In [5]:
#print all target labels
import pandas as pd
print(df['target'].unique())

[2 1 0]


In [6]:
#6.prepare subset of categories alt.athhesum com.graphics sci.space
from sklearn.datasets import fetch_20newsgroups

# Define categories to extract
categories = ['alt.atheism', 'comp.graphics', 'sci.space']

# Load subset of the dataset
newsgroups_subset = fetch_20newsgroups(subset='train', categories=categories, remove=('headers', 'footers', 'quotes'))

# Print number of documents per category
print(f"Total documents: {len(newsgroups_subset.data)}")
print(f"Target labels: {set(newsgroups_subset.target)}")  # Numeric labels
print(f"Target names: {newsgroups_subset.target_names}")  # Category names


/home/user/ml/notebookenv/lib/python3.12/site-packages/sklearn/datasets/_base.py:1519: UserWarning: Retry downloading from url: https://ndownloader.figshare.com/files/5975967
  warnings.warn(f"Retry downloading from url: {remote.url}")


URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

In [9]:
#7.load 20 news group train subset with three categroies lt.athesim ; comp.graphic
from sklearn.datasets import fetch_20newsgroups

# Define categories to extract
categories = ['alt.atheism', 'comp.graphics', 'sci.space']  # Modify if needed

# Load the dataset (training subset)
newsgroups_train = fetch_20newsgroups(subset='train', categories=categories, remove=('headers', 'footers', 'quotes'))

# Print dataset details
print(f"Total documents: {len(newsgroups_train.data)}")
print(f"Target labels: {set(newsgroups_train.target)}")  # Numeric labels
print(f"Target names: {newsgroups_train.target_names}")  # Category names


Total documents: 1657
Target labels: {np.int64(0), np.int64(1), np.int64(2)}
Target names: ['alt.atheism', 'comp.graphics', 'sci.space']


In [10]:
#8.load 20 news group test subset categories alt.athesim comp.graphics

from sklearn.datasets import fetch_20newsgroups

# Define categories to extract
categories = ['alt.atheism', 'comp.graphics', 'sci.space']

# Load the dataset (test subset)
newsgroups_test = fetch_20newsgroups(subset='test', categories=categories, remove=('headers', 'footers', 'quotes'))

# Print dataset details
print(f"Total documents: {len(newsgroups_test.data)}")
print(f"Target labels: {set(newsgroups_test.target)}")  # Numeric labels
print(f"Target names: {newsgroups_test.target_names}")  # Category names


Total documents: 1102
Target labels: {np.int64(0), np.int64(1), np.int64(2)}
Target names: ['alt.atheism', 'comp.graphics', 'sci.space']


In [1]:
#9.print new training set target names(labels)
# Print target names (labels)
print("Target Names (Labels):")
print(newsgroups_test.target_names)

Target Names (Labels):


NameError: name 'newsgroups_test' is not defined

In [4]:
#10.print new training data of 5th article
print(newsgroups_train.data[4])

NameError: name 'newsgroups_train' is not defined

In [13]:
#11.print shape of data and targets
from sklearn.datasets import fetch_20newsgroups

# Define categories to extract
categories = ['alt.atheism', 'comp.graphics', 'sci.space']

# Load the dataset (training subset)
newsgroups_train = fetch_20newsgroups(subset='train', categories=categories, remove=('headers', 'footers', 'quotes'))

# Print the shape of data and targets
print("Number of documents (data shape):", len(newsgroups_train.data))
print("Number of target labels:", len(newsgroups_train.target))  

Number of documents (data shape): 1657
Number of target labels: 1657


In [14]:
#12.print training set filenames

In [15]:
#13.by using Countvectorizer train data ito numerical format considering
from sklearn.feature_extraction.text import CountVectorizer
mf=(df.head())
vectorizer = CountVectorizer()

# Convert text data into numerical form
X = vectorizer.fit_transform(mf.text)

# Display the vocabulary (words mapped to indices)
print("Vocabulary:", vectorizer.vocabulary_)

# Display the transformed data as an array
print("Numerical representation:\n", X.toarray())

Vocabulary: {'from': 186, 'mccall': 269, 'mksol': 283, 'dseg': 153, 'ti': 426, 'com': 106, 'fred': 184, '575': 20, '3539': 12, 'subject': 402, 're': 348, 'satellite': 366, 'around': 59, 'pluto': 331, 'mission': 282, 'organization': 314, 'texas': 410, 'instruments': 223, 'inc': 216, 'lines': 246, '24': 7, 'in': 215, '1993apr30': 6, '004311': 0, 'aurora': 66, 'alaska': 37, 'edu': 158, 'nsmca': 303, 'writes': 484, 'being': 78, 'wierd': 475, 'again': 36, 'so': 387, 'be': 74, 'warned': 462, 'is': 228, 'there': 419, 'plan': 327, 'to': 428, 'put': 343, 'each': 154, 'planet': 328, 'the': 415, 'solar': 389, 'system': 405, 'keep': 233, 'watch': 464, 'help': 200, 'it': 229, 'better': 80, 'ask': 63, 'questions': 344, 'before': 77, 'spout': 395, 'an': 46, 'opinion': 311, 'how': 207, 'about': 27, 'unmanned': 443, 'stay': 397, 'orbit': 313, 'and': 47, 'record': 352, 'things': 422, 'near': 292, 'on': 307, 'know': 236, 'strange': 401, 'idea': 211, 'but': 90, 'why': 474, 'not': 301, 'could': 123, 'do': 

In [16]:
#14.use bernouli NM for training  



In [18]:
#16.predict target labels for testing set
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split

# Step 1: Load the dataset (Assuming it's a CSV file with 'text' and 'label' columns)
df = pd.read_csv("newsgroups_train.csv")  # Replace with your actual dataset path
test_df = pd.read_csv("newsgroups_test.csv")  # Replace with your actual test dataset path

# Step 2: Extract features and labels
train_documents = df["text"].astype(str)  # Convert text column to string
train_labels = df["target"]  # Labels (0, 1, 2, etc.)

test_documents = test_df["text"].astype(str)  # Convert test text column to string

# Step 3: Convert text into numerical format using CountVectorizer
vectorizer = CountVectorizer(binary=True)
X_train = vectorizer.fit_transform(train_documents)
X_test = vectorizer.transform(test_documents)  # Transform test data using the same vectorizer

# Step 4: Train Bernoulli Naïve Bayes model
model = BernoulliNB()
model.fit(X_train, train_labels)

# Step 5: Predict target values for test data
predictions = model.predict(X_test)

# Step 6: Save or print predictions
test_df["predicted_label"] = predictions  # Add predictions to test dataframe
test_df.to_csv("predictions.csv", index=False)  # Save predictions to CSV
print(test_df[["text", "predicted_label"]])  # Display results


                                                   text  predicted_label
0     From: mccall@mksol.dseg.ti.com (fred j mccall ...                2
1     From: "Changyaw Wang" <wangc@cs.indiana.edu>\n...                1
2     From: lioness@maple.circa.ufl.edu\nSubject: Te...                1
3     From: hotopp@ami1.bwi.wec.com (Daniel T. Hotop...                1
4     From: Ad-Robot@bobsbox.rent.com (Robotic Posti...                1
...                                                 ...              ...
1097  From: malek@pi.titech.ac.jp (Zidouri Abdelmale...                1
1098  From: livesey@solntze.wpd.sgi.com (Jon Livesey...                0
1099  From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...                0
1100  From: beck@irzr17.inf.tu-dresden.de (Andre Bec...                1
1101  From: 18084TM@msu.edu (Tom)\nSubject: Billboar...                2

[1102 rows x 2 columns]


In [19]:
#17.find accuracy score on test set
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score

# Step 1: Load the dataset (Assuming it's a CSV file with 'text' and 'label' columns)
df = pd.read_csv("newsgroups_train.csv")  # Replace with your actual training dataset path
test_df = pd.read_csv("newsgroups_test.csv")  # Replace with your actual test dataset path

# Step 2: Extract features and labels
train_documents = df["text"].astype(str)  # Convert text column to string
train_labels = df["target"]  # Labels (0, 1, 2, etc.)

test_documents = test_df["text"].astype(str)  # Convert test text column to string
test_labels = test_df["target"]  # True labels for accuracy calculation

# Step 3: Convert text into numerical format using CountVectorizer
vectorizer = CountVectorizer(binary=True)
X_train = vectorizer.fit_transform(train_documents)
X_test = vectorizer.transform(test_documents)  # Transform test data using the same vectorizer

# Step 4: Train Bernoulli Naïve Bayes model
model = BernoulliNB()
model.fit(X_train, train_labels)

# Step 5: Predict target values for test data
predictions = model.predict(X_test)

# Step 6: Compute Accuracy Score
accuracy = accuracy_score(test_labels, predictions)
print(f"Accuracy Score: {accuracy:.4f}")  # Print accuracy with 4 decimal places


Accuracy Score: 0.8530


In [3]:
#18.use tfidvectorizer instead of count vectorizer
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score

# Step 1: Load the dataset (Assuming it's a CSV file with 'text' and 'label' columns)
df = pd.read_csv("newsgroups_train.csv")  # Replace with your actual training dataset path
test_df = pd.read_csv("newsgroups_test.csv")  # Replace with your actual test dataset path

# Step 2: Extract features and labels
train_documents = df["text"].astype(str)  # Convert text column to string
train_labels = df["target"]  # Labels (0, 1, 2, etc.)

test_documents = test_df["text"].astype(str)  # Convert test text column to string
test_labels = test_df["target"]  # True labels for accuracy calculation

# Step 3: Convert text into numerical format using TfidfVectorizer
vectorizer = TfidfVectorizer(binary=True)  # TF-IDF representation
X_train = vectorizer.fit_transform(train_documents)
X_test = vectorizer.transform(test_documents)  # Transform test data using the same vectorizer

# Step 4: Train Bernoulli Naïve Bayes model
model = BernoulliNB()
model.fit(X_train, train_labels)

# Step 5: Predict target values for test data
predictions = model.predict(X_test)

# Step 6: Compute Accuracy Score
accuracy = accuracy_score(test_labels, predictions)
print(f"Accuracy Score: {accuracy:.4f}")  # Print accuracy with 4 decimal places


FileNotFoundError: [Errno 2] No such file or directory: 'newsgroups_train.csv'

In [2]:
#15. By using countvectorizer convert test data into numeric format considering only
f=pd.read_csv('newsgroups_test.csv')
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

# Convert text data into numerical form
X = vectorizer.fit_transform(df.text)

# Display the vocabulary (words mapped to indices)
print("Vocabulary:", vectorizer.vocabulary_)

# Display the transformed data as an array
md=print("Numerical representation:\n", X.toarray())

NameError: name 'pd' is not defined